<div class="container mt-5">
    <form action="" method="post">
        <label>Nome:</label>
        <input id="name" name="name" type="text" class="form-control">
        <br>
        <label>E-mail:</label>
        <input id="email" name="email" type="email" class="form-control">
        <br>
        <label>Telefone:</label>
        <input id="phone" name="number" type="number" class="form-control">
        <br>
        <button id="enviar" class="btn btn-danger">Enviar</button>
    </form>
</div>